# Copyright (c) 2025 Qualcomm Innovation Center, Inc. All rights reserved.
# SPDX-License-Identifier: BSD-3-Clause-Clear

# select disk type emmc | nand | nvme | ufs Mandatory
# disk size in bytes Mandatory
# options if not explicitly provide

--disk --type=nvme --size=68719476736 --write-protect-boundary=65536 --sector-size-in-bytes=512 --grow-last-partition

# per partition entry
# mandatory options:
#   --lun (mandatory for UFS, emmc no need this)
#   --name
#   --size in bytes
#   --type-guid
# optional options: (defaults used if not provided)
#   --attributes  1000000000000004
#   --filename    ""
#   --readonly    true
#   --sparse      false

# This is physical partition 0
--partition --name=ToolsFv --size=1024KB --type-guid=97745ABA-135A-44C3-9ADC-05616173C24C --filename=tools.fv
--partition --name=ToolsFv_BACKUP --size=1024KB --type-guid=A3381699-350C-465E-BD5D-FA3AB901A39A --filename=tools.fv
--partition --name=LogFs --size=16384KB --type-guid=BC0330EB-3410-4951-A617-03898DBE3372 --filename=logfs_ufs_8mb.bin
--partition --name=EnterpriseFv --size=1024KB --type-guid=B7524B2D-0A91-49A2-AA5E-BDA266699D49
--partition --name=UpdateCapsule --size=71680KB --type-guid=C80325BA-7EC2-4A30-B2F7-18F646086185
--partition --name=NHLOS --size=122880KB --type-guid=FA4CBE53-31B5-4C23-9C1E-A01FEB966856 --filename=NON-HLOS.bin
--partition --name=core_nhlos_a --size=122880KB --type-guid=6690B4CE-70E9-4817-B9F1-25D64D888357
--partition --name=quantumsdk --size=1024KB --type-guid=AA9A5C4C-4F1F-7D3A-014A-22BD33BF7191
--partition --name=quantumfv --size=512KB --type-guid=80C23C26-C3F9-4A19-BB38-1E457DACEB09
--partition --name=quantumcontentfv --size=1024KB --type-guid=E12D830B-7F62-4F0B-B48A-8178C5BF3AC1
--partition --name=logdump --size=524288KB --type-guid=5AF80809-AABB-4943-9168-CDFC38742598
--partition --name=efi --size=1572864KB --type-guid=C12A7328-F81F-11D2-BA4B-00A0C93EC93B --filename=efi.bin
--partition --name=rootfs --size=33554432KB --type-guid=B921B045-1DF0-41C3-AF44-4C6F280D3FAE --filename=rootfs.img
